<ul class="list-inline list-unstyled">
    <li><a href="<?php echo Mage::getBaseUrl(); ?>"><?php echo $this->__('Home'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "about-magento-demo-store"; ?>"><?php echo $this->__('About'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "customer-service"; ?>"><?php echo $this->__('Customer Service'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "site_map"; ?>"><?php echo $this->__('Site Map'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "search-terms"; ?>"><?php echo $this->__('Search Terms'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "contact-us"; ?>"><?php echo $this->__('Contacts'); ?></a></li>
</ul>