<h3><?php echo $this->__('My account'); ?></h3>
<ul class="list-unstyled">
    <li><a href="<?php echo Mage::getBaseUrl() . "customer/account/login"; ?>"><?php echo $this->__('Sign In'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "checkout/cart"; ?>"><?php echo $this->__('View Cart'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "wishlist"; ?>"><?php echo $this->__('My Wishlist'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "track-my-order"; ?>"><?php echo $this->__('Track My Order'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "help"; ?>"><?php echo $this->__('Help'); ?></a></li>
</ul>