<h3><?php echo $this->__('Information'); ?></h3>
<ul class="list-unstyled">
    <li><a href="<?php echo Mage::getBaseUrl() . "about-magento-demo-store"; ?>"><?php echo $this->__('About Us'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "customer-service"; ?>"><?php echo $this->__('Customer Service'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "privacy-policy-cookie-restriction-mode"; ?>"><?php echo $this->__('Privacy Policy'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "site_map"; ?>"><?php echo $this->__('Site Map'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "search-terms"; ?>"><?php echo $this->__('Search Terms'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "advanced-search"; ?>"><?php echo $this->__('Advanced Search'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "orders-returns"; ?>"><?php echo $this->__('Orders And Returns'); ?></a></li>
    <li><a href="<?php echo Mage::getBaseUrl() . "contact-us"; ?>"><?php echo $this->__('Contact Us'); ?></a></li>
</ul>