<div class="container content-block">
    <div class="row home-page-first-line">
        <div class="content-block-1">
            <div class="img-collection">
                <img src="<?php echo $this->getSkinUrl('images/new-collection.png'); ?>"/>
            </div>
        </div>
        <div class="content-block-2">
            <div class="img-b2">
                <img src="<?php echo $this->getSkinUrl('images/b2.png'); ?>"/>
            </div>
            <div class="img-shoes">
                <img src="<?php echo $this->getSkinUrl('images/shoes.png'); ?>"/>
            </div>
        </div>
    </div>
    <div class="row home-page-second-line">
        <div class="content-block-1">
            <div class="free-shipping">
                <img src="<?php echo $this->getSkinUrl('images/free-shipping.png'); ?>"/>
            </div>
        </div>
        <div class="content-block-2">
            <img src="<?php echo $this->getSkinUrl('images/dresses.png'); ?>"/>
        </div>
    </div>
</div>