<div class="top">
    <h1><?php echo $this->__('Testimonials'); ?></h1>
    <div class="testimonials_form">
        <button type="button" class="btn submit-testimonials"><?php echo $this->__('Submit your Testimonial'); ?></button>
        <div class="testimonials_block_form">
            <?php if(!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                <div class="login-info">
                    <p>
                        <?php echo $this->__('Please'); ?>
                        <a href="<?php echo Mage::getBaseUrl() . "customer/account/login/"; ?>">
                            <?php echo $this->__('Login'); ?>
                        </a>
                        <?php echo $this->__('to add new testimonials'); ?>
                    </p>
                </div>
                <a class="btn btn-default form-close">Close</a>
            <?php else: ?>
                <?php $name = Mage::getSingleton('customer/session')->getCustomer()->getName(); ?>
                <p><?php echo $this->__('your testimonials ..'); ?></p>
                <form action="<?php echo Mage::getUrl('testimonials/index/save') ?>" id="my-custom-form" method="post">
                    <fieldset>
                        <ul>
                            <li>
                                <label for="customer_id"><?php echo $this->__('Author:'); ?></label>
                                <input type="text" class="form-control input-text" id="author" value="<?php echo $name; ?>" name="customer_id" />
                            </li>
                            <li>
                                <label for="content"><?php echo $this->__('Testimonial:'); ?></label>
                                <textarea type="text" id="content" name="content" class="form-control input-text" rows="3"></textarea>
                            </li>
                            <li class="form-button">
                                <button type="submit" value="Save" class="btn button-submit"><?php echo $this->__('Submit'); ?></button>
                                <a class="btn btn-default form-close">Close</a>
                            </li>
                        </ul>
                    </fieldset>
                </form>
            <?php endif ?>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<div class="testimonials">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php $collection = $this->getCollection(); ?>
    <?php if($collection->getSize()): ?>
        <?php foreach ($collection as $testimonial): ?>
            <p class="testimonials-content">
                <?php echo $testimonial->getContent(); ?>
            </p>
            <div class="triangle-down"></div>
            <h5 class="testimonials-author">
                <?php echo $testimonial->getCustomerId(); ?>
            </h5>
        <?php endforeach; ?>
        <?php echo $this->getPagerHtml(); ?>
    <?php else: ?>
        <p><?php echo $this->__('The collection is empty.'); ?></p>
    <?php endif ?>
</div>
<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('my-custom-form');
    //]]>
</script>
